### ISSUE TITLE
demo project does not work

### ISSUE THREAD

**Issue by antonkulaga** [coreyauger/scalajs-google-maps#1]
After fastOptJS-sing and running the demo project I get the following error (even when I run from localhost):

```
Cannot read property 'maps' of undefined
ScalaJSGMapExample.scala:124 Uncaught TypeError: Cannot read property 'maps' of undefined$c_Ldemo_ScalaJSGMapExample$.main__V @ ScalaJSGMapExample.scala:124$c_Ldemo_ScalaJSGMapExample$.$$js$exported$meth$main__O @ JSApp.scala:18$c_Ldemo_ScalaJSGMapExample$.main @ ScalaJSGMapExample.scala:11(anonymous function) @ index-fastopt.html:25
```

**Comment by coreyauger** [comment]
You must include google maps in your header

```
 <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=API_KEY"></script>
```

**Comment by antonkulaga** [comment]
Why did not you include it (or warning about absence of key) to the html then?

**Comment by coreyauger** [comment]
I suppose we could add it to the demo project ... although you are still going to have to register your own API key.

It is however clearly stated in the documentation ... and somewhat implied in the entire use of the project.
